<a href="https://colab.research.google.com/github/molinamarriott/eliminatorias/blob/main/introduccion_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducción a Pandas

Pandas es una biblioteca poderosa y flexible para la manipulación y análisis de datos en Python. Ofrece estructuras de datos como DataFrames y Series para trabajar con datos tabulares de manera eficiente.

### 1. Instalación y Carga de Pandas

In [ ]:
# Si no tienes pandas instalado, puedes usar el siguiente comando:
# !pip install pandas

import pandas as pd

### 2. Creación de un DataFrame

![2023-08-11-dataframes.jpg]()

In [ ]:
# Creando un DataFrame desde un diccionario
datos = {
    'Nombre': ['Ana', 'Luis', 'María', 'Pedro', 'Juana', 'Marta'],
    'Edad': [23, 30, 25, 40,60,70],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Sevilla', 'Guayaquil', 'Quito']
}

df = pd.DataFrame(datos)
df

  Nombre  Edad     Ciudad
0    Ana    23     Madrid
1   Luis    30  Barcelona
2  María    25   Valencia
3  Pedro    40    Sevilla
4  Juana    60  Guayaquil
5  Marta    70      Quito

### 3. Lectura de Archivos

In [ ]:
# Leer un archivo CSV (suponiendo que tienes un archivo 'archivo.csv')
# df = pd.read_csv('archivo.csv')

### 4. Exploración de Datos

In [ ]:
# Explorando el DataFrame
print(df.head())  # Muestra las primeras 5 filas
print(df.describe())  # Resumen estadístico de las columnas numéricas
print(df.info())  # Información del DataFrame

### 5. Selección de Datos

In [ ]:
# Seleccionando columnas
print(df['Nombre'])  # Selecciona la columna 'Nombre'

# Seleccionando filas por índice
print(df.iloc[1])  # Selecciona la segunda fila (índice 1)

# Selección condicional
print(df[df['Edad'] > 25])  # Filtra filas donde la edad es mayor que 25

### 6. Modificación de Datos

In [ ]:
# Agregar una nueva columna
df['Salario'] = [30000, 40000, 35000, 50000,10000, 800]
df

  Nombre  Edad       Ciudad  Salario
0    Ana    24       Madrid    30000
1   Luis    31    Barcelona    40000
2  María    26  Desconocido    35000
3  Pedro    41      Sevilla    50000
4  Juana    61    Guayaquil    10000
5  Marta    71        Quito      800

In [ ]:
# Modificar valores
df.loc[0, 'Edad'] = 24
df

  Nombre  Edad       Ciudad  Salario
0    Ana    24       Madrid    30000
1   Luis    31    Barcelona    40000
2  María    26  Desconocido    35000
3  Pedro    41      Sevilla    50000
4  Juana    61    Guayaquil    10000
5  Marta    71        Quito      800

### 7. Operaciones con Datos

In [ ]:
# Operaciones matemáticas
df['Edad'] = df['Edad'] + 1  # Incrementa en 1 la edad de todos
df['Salario_aumento'] = df['Salario'] * 1.1  # Aumenta el salario en un 10%
df

  Nombre  Edad       Ciudad  Salario  Salario_aumento
0    Ana    25       Madrid    30000          33000.0
1   Luis    32    Barcelona    40000          44000.0
2  María    27  Desconocido    35000          38500.0
3  Pedro    42      Sevilla    50000          55000.0
4  Juana    62    Guayaquil    10000          11000.0
5  Marta    72        Quito      800            880.0

### 9. Eliminación de Filas o Columnas

In [ ]:
# Eliminar una columna
df.drop('Salario', axis=1, inplace=True)
df

In [ ]:
# Eliminar una fila
df.drop(1, axis=0, inplace=True)
df

# 10.Función apply:
La función apply permite aplicar funciones personalizadas a filas o columnas enteras de un DataFrame. Es increíblemente útil para transformaciones complejas en tus datos, incluso si son operaciones que no están vectorizadas de forma nativa.

# 11. Valores nulos

In [ ]:
datos = {
    'Nombre': ['Andres','Ana', 'Luis', 'María', 'Pedro', 'Sofía', 'Estefania', 'Veronica'],
    'Ocupación': ['Empleado','Empleado', 'Desempleado', 'Empleado', 'Empleado', 'Desempleado', 'Empleado', 'Empleado'],
    'Ingreso': [None,4000, None, 5000, 4500, None, 2000, 2500],
    'cargo': ['Subgerente','Gerente', None, 'Gerente', 'Gerente', None, 'Subgerente','Subgerente' ],

}
df_valores = pd.DataFrame(datos)
df_valores

      Nombre    Ocupación  Ingreso       cargo
0     Andres     Empleado      NaN  Subgerente
1        Ana     Empleado   4000.0     Gerente
2       Luis  Desempleado      NaN        None
3      María     Empleado   5000.0     Gerente
4      Pedro     Empleado   4500.0     Gerente
5      Sofía  Desempleado      NaN        None
6  Estefania     Empleado   2000.0  Subgerente
7   Veronica     Empleado   2500.0  Subgerente